import 'package:flutter/material.dart';
import '../database/booking_dao.dart';
import '../models/booking.dart';

class BookingProvider extends ChangeNotifier {
  final BookingDAO _bookingDao = BookingDAO();
  List<Booking> _bookings = [];
  List<String> _selectedSeats = [];

  List<String> get selectedSeats => _selectedSeats;
  List<Booking> get bookings => _bookings;

  void selectSeat(String seatLabel) {
    if (_selectedSeats.contains(seatLabel)) {
      _selectedSeats.remove(seatLabel);
    } else {
      _selectedSeats.add(seatLabel);
    }
    notifyListeners();
  }

  Future<void> bookSeats({
    required int userId,
    required int showtimeId,
    required double pricePerSeat,
  }) async {
    if (_selectedSeats.isEmpty) return;

    double totalPrice = _selectedSeats.length * pricePerSeat;

    Booking newBooking = Booking(
      id: 0, // ID is auto-generated by SQLite
      userId: userId,
      showtimeId: showtimeId,
      seats: _selectedSeats,
      totalPrice: totalPrice,
      qrCode: "QR_${DateTime.now().millisecondsSinceEpoch}", // Placeholder QR
    );

    await _bookingDao.insertBooking(newBooking);
    _selectedSeats.clear();
    await fetchUserBookings(userId);
  }

  Future<void> fetchUserBookings(int userId) async {
    _bookings = await _bookingDao.getBookingsByUserId(userId);
    notifyListeners();
  }
}
